image: Ubuntu2204

stack: node 20

branches:
  only:
    - main

cache:
  - node_modules
  - ~/.yarn-cache

environment:
  GITHUB_TOKEN:
    secure: YOUR_ENCRYPTED_TOKEN
  RENDER_TOKEN:
    secure: YOUR_RENDER_TOKEN
  NODE_ENV: production
  ASSET_PATH: '/sse-ws-chat/'

install:
  - yarn install --frozen-lockfile
  - yarn workspace @sse-ws-chat/backend install --frozen-lockfile
  - yarn workspace @sse-ws-chat/frontend install --frozen-lockfile

build_script:
  - yarn build

test_script:
  - yarn format:check

deploy_script:
  - git config --global user.name "AppVeyor"
  - git config --global user.email "ci@appveyor.com"
  - echo "https://$GITHUB_TOKEN@github.com" > ~/.git-credentials
  - git config --global credential.helper store
  - yarn workspace @sse-ws-chat/frontend deploy

  - cd backend
  - git init
  - git add .
  - git commit -m "Deploy to Render"
  - git push --force "https://api.render.com/deploy/srv-YOUR-RENDER-SERVICE-ID?key=$RENDER_TOKEN" main

notifications:
  - provider: Email
    to:
        - shalamovartem6@mail.ru
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true