image: Ubuntu2204

stack: node 20

branches:
  only:
    - main

cache:
  - node_modules
  - .yarn-cache

environment:
  GITHUB_TOKEN:
    secure: YOUR_ENCRYPTED_TOKEN  # Получить в GitHub -> Settings -> Developer settings -> Personal access tokens
  RENDER_TOKEN:
    secure: YOUR_RENDER_TOKEN     # Получить в Render Dashboard

install:
  - yarn install

build_script:
  - yarn build

test_script:
  - yarn lint

deploy_script:
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - git config --global credential.helper store
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - yarn deploy

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true