image: Ubuntu2204

stack: node 20

branches:
  only:
    - main

cache:
  - node_modules
  - .yarn-cache

environment:
  GITHUB_TOKEN:
    secure: YOUR_ENCRYPTED_TOKEN
  RENDER_TOKEN:
    secure: YOUR_RENDER_TOKEN
  NODE_ENV:
    value: production
  ASSET_PATH:
    value: '/sse-ws-chat/'

install:
  - yarn install --frozen-lockfile

build_script:
  - yarn build

test_script:
  - yarn lint

deploy_script:
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - git config --global credential.helper store
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - yarn deploy

  - git push https://api.render.com/deploy/srv-YOUR-RENDER-SERVICE-ID?key=$RENDER_TOKEN main

notifications:
  - provider: Email
    to:
        - shalamovartem6@mail.ru
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true

build:
  verbosity: detailed