services:
  - type: web
    name: sse-ws-chat-backend
    runtime: node
    buildCommand: yarn install
    startCommand: yarn start:server
    plan: free
    region: singapore
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 7070
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1